# Generated by Django 4.2.6 on 2023-11-02 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_remove_post_category_categorypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='image',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
